apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  creationTimestamp: null
  name: codewind-nodejs-express-dkh
  namespace: codewind-nodejs-express-dkh
spec:
  applicationImage: dev.local/codewind-nodejs-express-dkh
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: codewind-nodejs-express-dkh
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 3000
    type: NodePort
  stack: nodejs-express
  version: 1.0.0
